<?xml version="1.0" encoding="utf-8"?><Database Name="Database1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Database1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LECTURER" Member="LECTURERs">
    <Type Name="LECTURER">
      <Column Name="lect_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="L_name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="L_title" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="LECTURER_MODULE" Member="MODULEs" ThisKey="lect_ID" OtherKey="lect_ID" Type="MODULE" />
    </Type>
  </Table>
  <Table Name="dbo.MODULE" Member="MODULEs">
    <Type Name="MODULE">
      <Column Name="mod_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="semester" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mod_credits" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lect_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MODULE_REGISTERED" Member="REGISTEREDs" ThisKey="mod_ID" OtherKey="mod_ID" Type="REGISTERED" />
      <Association Name="LECTURER_MODULE" Member="LECTURER" ThisKey="lect_ID" OtherKey="lect_ID" Type="LECTURER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.POSTGRADUATE" Member="POSTGRADUATEs">
    <Type Name="POSTGRADUATE">
      <Column Name="stud_number" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="full_time" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="thesis_title" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="STUDENT_POSTGRADUATE" Member="STUDENT" ThisKey="stud_number" OtherKey="stud_number" Type="STUDENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.STUDENT" Member="STUDENTs">
    <Type Name="STUDENT">
      <Column Name="stud_number" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="stud_contNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date_of_birth" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="STUDENT_POSTGRADUATE" Member="POSTGRADUATE" ThisKey="stud_number" OtherKey="stud_number" Type="POSTGRADUATE" Cardinality="One" />
      <Association Name="STUDENT_UNDERGARDUATE" Member="UNDERGARDUATE" ThisKey="stud_number" OtherKey="stud_number" Type="UNDERGARDUATE" Cardinality="One" />
      <Association Name="STUDENT_REGISTERED" Member="REGISTEREDs" ThisKey="stud_number" OtherKey="stud_number" Type="REGISTERED" />
    </Type>
  </Table>
  <Table Name="dbo.UNDERGARDUATE" Member="UNDERGARDUATEs">
    <Type Name="UNDERGARDUATE">
      <Column Name="stud_number" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="extended_P" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="year_study" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="STUDENT_UNDERGARDUATE" Member="STUDENT" ThisKey="stud_number" OtherKey="stud_number" Type="STUDENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.REGISTERED" Member="REGISTEREDs">
    <Type Name="REGISTERED">
      <Column Name="stud_number" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mod_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="marks" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MODULE_REGISTERED" Member="MODULE" ThisKey="mod_ID" OtherKey="mod_ID" Type="MODULE" IsForeignKey="true" />
      <Association Name="STUDENT_REGISTERED" Member="STUDENT" ThisKey="stud_number" OtherKey="stud_number" Type="STUDENT" IsForeignKey="true" />
    </Type>
  </Table>
</Database>